services:
  client:
    image: edwin98carlsson/ts-animations-client:latest
    depends_on:
      - server
    networks:
      - app-network
    ports:
      - '3000:80'

  server:
    image: edwin98carlsson/ts-animations-server:latest
    networks:
      - app-network
    expose:
      - '4000'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - '5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '8080:80'
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  postgres_data:
