listen_addresses = '*'
port = 5432
max_connections = 100

# Write-ahead logging
synchronous_commit = off
wal_writer_delay = 2000ms
wal_buffers = 16MB
checkpoint_timeout = 30min
max_wal_size = 2GB
min_wal_size = 512MB

# Checkpoints
checkpoint_completion_target = 0.9

# Memory tuning
shared_buffers = 512MB
effective_cache_size = 2GB

# Other
log_min_duration_statement = 1000


log_destination = 'stderr'
logging_collector = on
log_directory = 'pg_log'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_truncate_on_rotation = on
log_rotation_age = 1d
log_rotation_size = 10MB
