name: Build and Push ts-animations Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: ts-animations

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      STATIC_JWT: ${{ secrets.STATIC_JWT }}
      PGADMIN_EMAIL: ${{ secrets.PGADMIN_EMAIL }}
      PGADMIN_PASSWORD: ${{ secrets.PGADMIN_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Write .env file
        run: |
          cat <<EOF > .env
          VITE_BACKEND_URL=${VITE_BACKEND_URL}
          SERVER_PORT=${SERVER_PORT}
          POSTGRES_USER=${POSTGRES_USER}
          POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          POSTGRES_DB=${POSTGRES_DB}
          STATIC_JWT=${STATIC_JWT}
          PGADMIN_EMAIL=${PGADMIN_EMAIL}
          PGADMIN_PASSWORD=${PGADMIN_PASSWORD}
          EOF

      - name: Restore Docker cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ runner.os }}-

      - name: Build and push client image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}-client:latest
          build-args: |
            VITE_BACKEND_URL=${{ env.VITE_BACKEND_URL }}
            SERVER_PORT=${{ env.SERVER_PORT }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-client,mode=max

      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}-server:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-server,mode=max

      - name: Consolidate Docker cache
        run: |
          rm -rf /tmp/.buildx-cache
          mkdir -p /tmp/.buildx-cache
          cp -r /tmp/.buildx-cache-client/. /tmp/.buildx-cache || true
          cp -r /tmp/.buildx-cache-server/. /tmp/.buildx-cache || true
